const companySymbolMap = {
    apple: "AAPL",
    tesla: "TSLA",
    microsoft: "MSFT",
    google: "GOOGL",
    alphabet: "GOOGL",
    amazon: "AMZN",
    meta: "META",
    facebook: "META",
    netflix: "NFLX",
    nvidia: "NVDA",
    amd: "AMD",
    intel: "INTC",
    adobe: "ADBE",
    oracle: "ORCL",
    ibm: "IBM",
    uber: "UBER",
    spotify: "SPOT",
    paypal: "PYPL",
    reliance: "RELIANCE.NS",
    tcs: "TCS.NS",
    infosys: "INFY.NS",
    hdfc: "HDFCBANK.NS",
};
export default companySymbolMap;